version: '3'
services:
  static:
    build: ./stripe_example
    image: stripe_example
    command: sh collect_static.sh
    env_file: ./stripe_example/dj.env.sample
    volumes:
      - static_content:/stripe_example/static:rw
  migration:
    restart: on-failure
    image: stripe_example
    command: python3 manage.py migrate
    env_file: ./stripe_example/dj.env.sample
    depends_on:
      - static
  database:
    image: postgres
    env_file: db.env.sample
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: stripe_example
    env_file: ./stripe_example/dj.env.sample
    depends_on:
      - database
    volumes:
      - static_content:/stripe_example/static:rw
    ports:
      - "8000:8000"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static_content:/var/www/static:ro
    depends_on:
      - web
    ports:
      - "80:80"
volumes:
  static_content:
  pgdata: